<Project>
  	<PropertyGroup>
        <LangVersion>latest</LangVersion>
		<TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Microsoft.EntityFrameworkCore</RootNamespace>
        <Authors>Ron Sijm</Authors>
		<Company>Ron Sijm</Company>
        <PackageProjectUrl>https://github.com/RonSijm/RonSijm.EF.Contexts</PackageProjectUrl>
	</PropertyGroup>
</Project>
