<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\BuildSettings\Common.props" />
  <Import Project="..\..\BuildSettings\NuGetVersioning.props" />

  <PropertyGroup>
    <Description>Core file-based database provider infrastructure for Entity Framework Core</Description>
    <Title>RonSijm.EF.FileStore.Core</Title>
    <PackageId>RonSijm.EF.FileStore.Core</PackageId>
    <PackageTags>Entity Framework Core;EF Core;File Store;Database Provider</PackageTags>
    <PackageOutputPath>..\..\packages</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
  </ItemGroup>

</Project>

