<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\BuildSettings\Common.props" />
  <Import Project="..\..\BuildSettings\NuGetVersioning.props" />

  <PropertyGroup>
    <Description>JSON file database provider for Entity Framework Core</Description>
    <Title>RonSijm.EF.Json</Title>
    <PackageId>RonSijm.EF.Json</PackageId>
    <PackageTags>Entity Framework Core;EF Core;JSON;Database Provider</PackageTags>
    <PackageOutputPath>..\..\packages</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RonSijm.EF.FileStore.Core\RonSijm.EF.FileStore.Core.csproj" />
  </ItemGroup>

</Project>

